#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

SHELL=/bin/zsh
EDITOR=nvim
TERMINAL=/usr/bin/kitty

if [ ! -x "$(command -v tmux)" ]
then
    echo 'TMUX não encontrado!'
    exit
fi

if [ ! -x "$(command -v wmctrl)" ]
then
    echo 'wmctrl não encontrado!'
    exit
fi

set +e
wmctrl -a $SHELL
if [ $? = 1 ]
then
    $TERMINAL
    sleep 1
fi
set -e

tmux new-window $EDITOR $@
