#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

SHELL=zsh
EDITOR=nvim
TERMINAL=kitty

if [ ! -x "$(command -v tmux)" ]
then
    echo 'TMUX não encontrado!'
    exit
fi

if [ ! -x "$(command -v wmctrl)" ]
then
    echo 'wmctrl não encontrado!'
    exit
fi

set +e
wmctrl -a $SHELL
if [ $? = 1 ]
then
    $TERMINAL
fi
set -e

sleep 1
tmux new-window $EDITOR "$@"
