#!/bin/bash

container_name="mongo"
volume_name="mongo-data"

docker volume inspect "$volume_name" > /dev/null
if [[ $? != 0 ]]
then
    docker volume create "$volume_name"
fi

docker container inspect "$container_name" > /dev/null
if [[ $? == 0 ]]
then
    docker start "$container_name"
else
    docker run \
        --name "$container_name" \
        --restart=always \
        --env MONGO_INITDB_ROOT_USERNAME=root \
        --env MONGO_INITDB_ROOT_PASSWORD=secret \
        --volume "$volume_name:/data/db" \
        --publish "27017:27017" \
        --detach \
        mongo
fi
