#!/bin/bash

container_name="postgres"
volume_name="postgres-data"

docker volume inspect "$volume_name" > /dev/null
if [[ $? != 0 ]]
then
    docker volume create "$volume_name"
fi

docker container inspect "$container_name" > /dev/null
if [[ $? == 0 ]]
then
    docker start "$container_name"
else
    docker run \
        --name "$container_name" \
        --restart=always \
        -e POSTGRES_PASSWORD=secret \
        -v "$volume_name:/var/lib/postgresql/data" \
        -p '5432:5432' \
        -d \
        postgres
fi
