#!/usr/bin/env python

import json
import shutil
import shlex
import subprocess
import argparse


class SubcommandHelpFormatter(argparse.RawDescriptionHelpFormatter):
    def _format_action(self, action):
        parts = super()._format_action(action)
        if action.nargs == argparse.PARSER:
            parts = "\n".join(parts.split("\n")[1:])
        return parts


def load_config_file(path):
    with open(path) as j:
        return json.load(j)
    return {}


def command_exists(cmd):
    return shutil.which(cmd)


def run_command(command, packages, shell=False):
    args = ([command] if isinstance(command, str) else command) + packages
    with subprocess.Popen(args, shell=shell) as _:
        print("{}".format(' '.join(args)))


def install_action(args):
    configs = load_config_file(args.file)

    managers = configs.get('managers', [])
    for data in managers:
        package_list = []
        command = data.get('install-command')
        if command:
            for p in data['packages']:
                cmd, pkg = p['command'], p['package']

                assert cmd and pkg

                if command_exists(cmd):
                    continue

                package_list.append(pkg)

            if not package_list:
                continue

            run_command(shlex.split(command), package_list)
        else:
            for p in data['packages']:
                cmd, install_cmd = p.get('command'), p.get('install-command')

                if not install_cmd:
                    continue

                if command_exists(cmd):
                    continue

                run_command(install_cmd, [], True)


def update_action(args):
    configs = load_config_file(args.file)

    managers = configs.get('managers', [])
    for data in managers:
        package_list = []
        command = data.get('update-command', None)
        if command:
            for p in data['packages']:
                pkg = p
                if not isinstance(p, str):
                    pkg = p['package']

                assert pkg

                package_list.append(pkg)

            if not package_list:
                continue

            run_command(shlex.split(command), package_list)
        else:
            for p in data['packages']:
                run_command(p['update-command'], [], True)


def main():
    parser = argparse.ArgumentParser(
        prog='cpm',
        description='Customer Package Manager',
        formatter_class=SubcommandHelpFormatter,
        usage='%(prog)s [options] <command>'
    )
    parser.add_argument('-f', dest='file', help='a cpm package configs')

    actions_parser = parser.add_subparsers(title='commands')
    install_parser = actions_parser.add_parser(
        'install', help='Install packages')
    install_parser.set_defaults(func=install_action)
    update_parse = actions_parser.add_parser(
        'update', help='Update packages')
    update_parse.set_defaults(func=update_action)

    parser.set_defaults(file='cpm.json', func=lambda _: parser.print_help())

    args = parser.parse_args()
    args.func(args)


if __name__ == '__main__':
    main()
