FROM archlinux

RUN : \
    && pacman -Syu --noconfirm \
    && pacman -S --noconfirm ansible sudo \
    && :

RUN : \
    && useradd -s /usr/bin/bash --create-home -G wheel testuser \
    && printf "123\n123\n" | passwd testuser \
    && echo "%wheel ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/wheel \
    && :

USER testuser

WORKDIR /home/testuser/ansible
