---
  - hosts: localhost
    tasks:
      - name: Install default packages
        apt:
          pkg:
            - curl
            - git
          state: present
      - name: Install chezmoi
        shell:
          cmd: curl -fsLS git.io/chezmoi | BINDIR=$HOME/.local/bin bash -
          warn: false
