#!/bin/bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

declare options=("alacritty
bspwm
cpm
dunst
polybar
sxhkd
nvim
zsh
tmux
ssh")

choice=$(echo -e "${options[@]}" | fzf)

case "$choice" in
    alacritty)
        choice="$HOME/.config/alacritty/alacritty.yml"
        ;;
    bspwm)
        choice="$HOME/.config/bspwm/bspwmrc"
        ;;
    cpm)
        choice="$HOME/.config/cpm/config.json"
        ;;
    dunst)
        choice="$HOME/.config/dunst/dunstrc"
        ;;
    polybar)
        choice="$HOME/.config/polybar/config"
        ;;
    sxhkd)
        choice="$HOME/.config/sxhkd/sxhkdrc"
        ;;
    nvim)
        choice="$HOME/.config/nvim/init.vim"
        ;;
    zsh)
        choice="$HOME/.zshrc"
        ;;
    tmux)
        choice="$HOME/.tmux.conf"
        ;;
    ssh)
        choice="$HOME/.ssh/config"
        ;;
    *)
        exit 1
        ;;
esac

$EDITOR $choice
