#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

MYREPOS_CONFIG_DIR=${MYREPOS_CONFIG_DIR:-$HOME/.config/myrepos}
repos_filepath="$MYREPOS_CONFIG_DIR/repos"

mkdir -p "$MYREPOS_CONFIG_DIR"

repos=
[[ -f $repos_filepath ]] && repos=$(cat $repos_filepath)

for repo in $repos
do
    [[ -d "$repo" ]] && (
        cd "$repo"
        echo "$repo"
        $@
    ) || echo "$repo not found"
done
